### ISSUE TITLE
Dragalia Life 450: Fire-Roasted Friendship not displaying

### ISSUE THREAD

**Issue by SMScep** [GimoTheBeast/dragaliaLifeIndex#1]
Hi, on the Dragalia Life archive, the image for comic 450 (Fire-Roasted Friendship) doesn't display. Tested on multiple devices including in incognito mode.

**Comment by GimoTheBeast** [comment]
Comic 450 was missing all languages, they have now been added.

**Comment by SMScep** [comment]
Thanks!
